
server:
  port: 8092

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: fotosUsuario

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"