server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
    registerWithEureka: false


#spring.cloud.discovery.enabled=true
#eureka.client.register-with-eureka=false
spring:
  cloud:
    discovery:
      enabled: true
    geteway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: servicio-cliente
          uri: http://localhost:8091/
          predicates:
            - Path=/cliente/**
        - id: servicio-foto
          uri: http://localhost:8092/
          predicates:
            - Path=/foto/**