
server:
  port: 8092

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: fotosUsuario

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
