
server:
  port: 8091

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bd_proyectoback?serverTimezone=UTC
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

feign:
  hystrix:
    anable: true
managemanet:
  endpoints:
    web:
      exposure:
        include: "*"